Gradients are essential for all optimizations. Autograd is a built in gradient calculator for pytorch.

In [1]:
import torch as tc

In [2]:
# randn gives a random from a normal distribution with mean 0 and sd 1
x = tc.randn(3, requires_grad=True)
x

tensor([-1.7552,  0.2298,  0.4503], requires_grad=True)

In [3]:
y = x + 2
y

tensor([0.2448, 2.2298, 2.4503], grad_fn=<AddBackward0>)

![Backpropagation Diagram](Data/Images/diagram_backprop.png "Backpropagation Diagram")

PyTorch will create a gradient function and apply it automatically during back propagation.

In [4]:
z = y * y * 2
z

tensor([ 0.1198,  9.9440, 12.0078], grad_fn=<MulBackward0>)

In [5]:
z = z.mean()
z

tensor(7.3572, grad_fn=<MeanBackward0>)

In [6]:
# Calculate the gradient for z with respect to x. dz/dx
z.backward()

In [7]:
# To see gradients stored
x.grad

tensor([0.3264, 2.9731, 3.2670])

In the background, this uses a Vector-Jacobian function to calculate the gradient.