Link to Lesson: https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2

In [33]:
import torch as tc

In [7]:
# 1D vector with 3 elements
x = tc.empty(3)
x

tensor([0., 0., 0.])

In [8]:
# 2D matrix 2 x 3
x = tc.empty(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Can list as many dimensions as you want.

In [9]:
# 2D matrix 2 x 3 filled with zeroes
x = tc.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# 2D matrix 2 x 3 filled with ones
x = tc.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# Check type
x.dtype

torch.float32

In [12]:
# Set type on initiation
# 2D matrix 2 x 3 filled with ones
x = tc.ones(2, 3, dtype=tc.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x.dtype

torch.float64

In [14]:
# Create Tensor
x = tc.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [15]:
# Arithmetic
x = tc.rand(2,2)
y = tc.rand(2,2)
print(x)
print(y)
z = x + y
z

tensor([[0.9613, 0.5407],
        [0.4901, 0.2296]])
tensor([[0.1352, 0.1090],
        [0.4880, 0.8422]])


tensor([[1.0965, 0.6497],
        [0.9780, 1.0718]])

In [16]:
# Inplace addition
z = tc.add(x,y)
z

tensor([[1.0965, 0.6497],
        [0.9780, 1.0718]])

In [17]:
# Multiplication
z = tc.mul(x,y)
z

tensor([[0.1300, 0.0589],
        [0.2391, 0.1934]])

In [18]:
# Multiplication
z = x * y
z

tensor([[0.1300, 0.0589],
        [0.2391, 0.1934]])

In [19]:
# Division
z = tc.div(x,y)
z

tensor([[7.1091, 4.9624],
        [1.0044, 0.2726]])

In [20]:
# Division
z = x / y
z

tensor([[7.1091, 4.9624],
        [1.0044, 0.2726]])

In [22]:
# Slicing
x = tc.rand(5,3)
x

tensor([[0.4749, 0.5510, 0.0300],
        [0.6482, 0.0953, 0.6088],
        [0.2324, 0.3983, 0.6198],
        [0.1233, 0.5497, 0.0504],
        [0.3171, 0.3273, 0.6754]])

In [23]:
x[:,0]

tensor([0.4749, 0.6482, 0.2324, 0.1233, 0.3171])

Getting values from slice

In [24]:
x[1,1]

tensor(0.0953)

In [25]:
# Can only use if there is only 1 item in tensor
x[1,1].item()

0.09530937671661377

In [27]:
# Reshaping
x = tc.rand(4,4)
x

tensor([[0.2044, 0.1292, 0.3150, 0.4918],
        [0.2039, 0.6464, 0.5271, 0.4352],
        [0.7227, 0.3436, 0.7638, 0.3245],
        [0.6408, 0.0920, 0.5512, 0.3820]])

In [30]:
# Elements specified must be the same
y = x.view(16)
y

tensor([0.2044, 0.1292, 0.3150, 0.4918, 0.2039, 0.6464, 0.5271, 0.4352, 0.7227,
        0.3436, 0.7638, 0.3245, 0.6408, 0.0920, 0.5512, 0.3820])

In [31]:
# Elements specified must be the same, can make it non specific
y = x.view(-1,8)
y

tensor([[0.2044, 0.1292, 0.3150, 0.4918, 0.2039, 0.6464, 0.5271, 0.4352],
        [0.7227, 0.3436, 0.7638, 0.3245, 0.6408, 0.0920, 0.5512, 0.3820]])

In [32]:
# Conversion between torch and numpy
import numpy as np

In [34]:
a = tc.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [35]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [36]:
type(b)

numpy.ndarray

If objects are on CPU and not GPU, they will share the same memory location and thus changing one will change the other

In [37]:
a.add_(1)
print(a)
b

tensor([2., 2., 2., 2., 2.])


array([2., 2., 2., 2., 2.], dtype=float32)

In [38]:
a += 1
print(a)
b

tensor([3., 3., 3., 3., 3.])


array([3., 3., 3., 3., 3.], dtype=float32)

If GPU is available

In [39]:
if tc.cuda.is_available():
    # Specify Device
    device = tc.device('cuda')
    # Create tensor on device
    x = tc.ones(5, device=device)
    # y is not on device
    y = tc.ones(5)
    # Send y to device
    y = y.to(device)
    # Z arithmetic is performed on gpu
    z = x + y
    # Numpy can only handle cpu
    # z.numpy() --> will result in error
    # Move z back to cpu
    z = z.to('cpu')

Adding paramenter requires_grad=True will tell torch that it will need to create gradient later in optimization steps

In [40]:
x = tc.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)