Link to Lesson: https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2

In [1]:
import torch as tc

In [2]:
# 1D vector with 3 elements
x = tc.empty(3)
x

tensor([2.3694e-38, 3.6013e-43, 0.0000e+00])

In [3]:
# 2D matrix 2 x 3
x = tc.empty(2, 3)
x

tensor([[-3., -2., -1.],
        [ 1.,  2.,  0.]])

Can list as many dimensions as you want.

In [4]:
# 2D matrix 2 x 3 filled with zeroes
x = tc.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# 2D matrix 2 x 3 filled with ones
x = tc.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# Check type
x.dtype

torch.float32

In [7]:
# Set type on initiation
# 2D matrix 2 x 3 filled with ones
x = tc.ones(2, 3, dtype=tc.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
x.dtype

torch.float64

In [9]:
# Create Tensor
x = tc.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [10]:
# Arithmetic
x = tc.rand(2,2)
y = tc.rand(2,2)
print(x)
print(y)
z = x + y
z

tensor([[0.4822, 0.2473],
        [0.6883, 0.2477]])
tensor([[0.0053, 0.8962],
        [0.4424, 0.8754]])


tensor([[0.4875, 1.1435],
        [1.1307, 1.1230]])

In [11]:
# Inplace addition
z = tc.add(x,y)
z

tensor([[0.4875, 1.1435],
        [1.1307, 1.1230]])

In [12]:
# Multiplication
z = tc.mul(x,y)
z

tensor([[0.0026, 0.2216],
        [0.3045, 0.2168]])

In [13]:
# Multiplication
z = x * y
z

tensor([[0.0026, 0.2216],
        [0.3045, 0.2168]])

In [14]:
# Division
z = tc.div(x,y)
z

tensor([[90.8583,  0.2759],
        [ 1.5559,  0.2829]])

In [15]:
# Division
z = x / y
z

tensor([[90.8583,  0.2759],
        [ 1.5559,  0.2829]])

In [16]:
# Slicing
x = tc.rand(5,3)
x

tensor([[0.2703, 0.9944, 0.8632],
        [0.0343, 0.1728, 0.2117],
        [0.6597, 0.8705, 0.7211],
        [0.6715, 0.3023, 0.5732],
        [0.4805, 0.9600, 0.8501]])

In [17]:
x[:,0]

tensor([0.2703, 0.0343, 0.6597, 0.6715, 0.4805])

Getting values from slice

In [18]:
x[1,1]

tensor(0.1728)

In [19]:
# Can only use if there is only 1 item in tensor
x[1,1].item()

0.17275142669677734

In [20]:
# Reshaping
x = tc.rand(4,4)
x

tensor([[0.2241, 0.3697, 0.1158, 0.4246],
        [0.0929, 0.8790, 0.1049, 0.7705],
        [0.3489, 0.1506, 0.7716, 0.0429],
        [0.3514, 0.1387, 0.4989, 0.9785]])

In [21]:
# Elements specified must be the same
y = x.view(16)
y

tensor([0.2241, 0.3697, 0.1158, 0.4246, 0.0929, 0.8790, 0.1049, 0.7705, 0.3489,
        0.1506, 0.7716, 0.0429, 0.3514, 0.1387, 0.4989, 0.9785])

In [22]:
# Elements specified must be the same, can make it non specific
y = x.view(-1,8)
y

tensor([[0.2241, 0.3697, 0.1158, 0.4246, 0.0929, 0.8790, 0.1049, 0.7705],
        [0.3489, 0.1506, 0.7716, 0.0429, 0.3514, 0.1387, 0.4989, 0.9785]])

In [23]:
# Conversion between torch and numpy
import numpy as np

In [24]:
a = tc.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [25]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
type(b)

numpy.ndarray

If objects are on CPU and not GPU, they will share the same memory location and thus changing one will change the other

In [27]:
a.add_(1)
print(a)
b

tensor([2., 2., 2., 2., 2.])


array([2., 2., 2., 2., 2.], dtype=float32)

In [28]:
a += 1
print(a)
b

tensor([3., 3., 3., 3., 3.])


array([3., 3., 3., 3., 3.], dtype=float32)

If GPU is available

In [31]:
if tc.cuda.is_available():
    print("CUDA Available")
    # Specify Device
    device = tc.device('cuda')
    # Create tensor on device
    x = tc.ones(5, device=device)
    # y is not on device
    y = tc.ones(5)
    # Send y to device
    y = y.to(device)
    # Z arithmetic is performed on gpu
    z = x + y
    # Numpy can only handle cpu
    # z.numpy() --> will result in error
    # Move z back to cpu
    z = z.to('cpu')

CUDA Available


Adding paramenter requires_grad=True will tell torch that it will need to create gradient later in optimization steps

In [32]:
x = tc.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)